INSERT INTO `pizzas`(`id`, `price`, `description`, `name`, `url_photo`) VALUES ('1','23.30','sdsdsasdsd','ciao','https://images.deepai.org/machine-learning-models/0c7ba850aa2443d7b40f9a45d9c86d3f/text2imgthumb.jpeg');
INSERT INTO `pizzas`(`id`, `price`, `description`, `name`, `url_photo`) VALUES ('2','23.30','sdsdsasdsd','cisao','https://images.deepai.org/machine-learning-models/0c7ba850aa2443d7b40f9a45d9c86d3f/text2imgthumb.jpeg');
INSERT INTO `pizzas`(`id`, `price`, `description`, `name`, `url_photo`) VALUES ('3','23.30','sdsdsasdsd','cissao','https://images.deepai.org/machine-learning-models/0c7ba850aa2443d7b40f9a45d9c86d3f/text2imgthumb.jpeg');
INSERT INTO `pizzas`(`id`, `price`, `description`, `name`, `url_photo`) VALUES ('4','23.30','sdsdsasdsd','cisssao','https://images.deepai.org/machine-learning-models/0c7ba850aa2443d7b40f9a45d9c86d3f/text2imgthumb.jpeg');
INSERT INTO `pizzas`(`id`, `price`, `description`, `name`, `url_photo`) VALUES ('5','23.30','sdsdsasdsd','ciassso','https://images.deepai.org/machine-learning-models/0c7ba850aa2443d7b40f9a45d9c86d3f/text2imgthumb.jpeg');
INSERT INTO `pizzas`(`id`, `price`, `description`, `name`, `url_photo`) VALUES ('6','23.30','sdsdsasdsd','ciassssso','https://images.deepai.org/machine-learning-models/0c7ba850aa2443d7b40f9a45d9c86d3f/text2imgthumb.jpeg');
INSERT INTO `pizzas`(`id`, `price`, `description`, `name`, `url_photo`) VALUES ('7','23.30','sdsdsasdsd','cisaoss','https://images.deepai.org/machine-learning-models/0c7ba850aa2443d7b40f9a45d9c86d3f/text2imgthumb.jpeg');
INSERT INTO `offers`(`end_date`, `id`, `pizza_id`, `start_date`, `title`) VALUES ('2023-12-10','1','2','2023-05-10','super offertuna');
INSERT INTO `offers`(`end_date`, `id`, `pizza_id`, `start_date`, `title`) VALUES ('2023-12-10','2','4','2023-05-10','super offertuna');
INSERT INTO `offers`(`end_date`, `id`, `pizza_id`, `start_date`, `title`) VALUES ('2023-10-10','3','5','2023-04-13','offertina');
INSERT INTO `offers`(`end_date`, `id`, `pizza_id`, `start_date`, `title`) VALUES ('2023-10-10','4','5','2023-04-13','regalato proprio');
INSERT INTO `ingredients`(`id`, `name`) VALUES ('1','ananas');
INSERT INTO `ingredients`(`id`, `name`) VALUES ('2','ippopotamo');
INSERT INTO `ingredients`(`id`, `name`) VALUES ('3','fegato');
INSERT INTO `ingredients`(`id`, `name`) VALUES ('4','componenti esotiche');
INSERT INTO roles (id, name) VALUES(1,'ADMIN');
INSERT INTO roles (id, name) VALUES(2,'USER');
INSERT INTO `users`(`email`, `first_name`, `last_name`, `password`) VALUES ('gino@gmail.com','gino','gino','{noop}gino');
INSERT INTO `users`(`email`, `first_name`, `last_name`, `password`) VALUES ('pino@gmail.com','pino','pino','{noop}pino');
INSERT INTO `users_roles`(`user_id`, `roles_id`) VALUES ('1','1');
INSERT INTO `users_roles`(`user_id`, `roles_id`) VALUES ('2','2');